/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RailSwitch {
        "styles": { track: string; target: { left: string; actor: string; right: string; }; };
    }
}
declare global {
    interface HTMLRailSwitchElement extends Components.RailSwitch, HTMLStencilElement {
    }
    var HTMLRailSwitchElement: {
        prototype: HTMLRailSwitchElement;
        new (): HTMLRailSwitchElement;
    };
    interface HTMLElementTagNameMap {
        "rail-switch": HTMLRailSwitchElement;
    }
}
declare namespace LocalJSX {
    interface RailSwitch {
        "styles"?: { track: string; target: { left: string; actor: string; right: string; }; };
    }
    interface IntrinsicElements {
        "rail-switch": RailSwitch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rail-switch": LocalJSX.RailSwitch & JSXBase.HTMLAttributes<HTMLRailSwitchElement>;
        }
    }
}
